name: Daily COPR

on:
  schedule:
    - cron: "30 6 * * 1-5"
  workflow_dispatch:

jobs:
  update_rpm:
    runs-on: ubuntu-latest
    name: Update RPM
    permissions:
      contents: write
    timeout-minutes: 5
    env:
      UPDATE_STATUS: "current"

    steps:
      - uses: actions/checkout@v4

      - name: Update RPM
        run: |
          # Update spec with HEAD commit of dependencies
          source ./scripts/update-rpm.sh --print-spec
          update_rpm

          # Output status to env
          echo "UPDATE_STATUS=$update_status" >> $GITHUB_ENV

      - name: Checkout submodules
        if: ${{ env.UPDATE_STATUS == 'updated' }}
        run: |
          bash ./scripts/checkout-deps.sh

      - name: Commit changes
        if: ${{ env.UPDATE_STATUS == 'updated' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CI"
          git commit -a -m "build(github-actions): automated update [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master

      - name: Build on COPR
        if: ${{ env.UPDATE_STATUS == 'updated' }}
        env:
          COPR_WEBHOOK: ${{ secrets.COPR_WEBHOOK }}
        run: |
          curl -X POST $COPR_WEBHOOK
